# Generated by Django 6.0.1 on 2026-02-09 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="configuration/%Y/%m/%d", verbose_name="Изображение"
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=255)),
                ("is_main", models.BooleanField(default=False)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.configuration",
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "Изображения",
                "ordering": ["order"],
            },
        ),
    ]
