# Generated by Django 6.0.1 on 2026-02-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_configurationimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationimage",
            name="image_webp",
            field=models.ImageField(
                blank=True, null=True, upload_to="configuration/webp/%Y/%m/%d"
            ),
        ),
        migrations.AlterField(
            model_name="configurationimage",
            name="image",
            field=models.ImageField(
                upload_to="configuration/original/%Y/%m/%d", verbose_name="Изображение"
            ),
        ),
    ]
