# Generated by Django 6.0.1 on 2026-02-09 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_configurationimage_image_webp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="configurationimage",
            old_name="image_webp",
            new_name="webp_image",
        ),
    ]
