# Generated by Django 6.0.1 on 2026-02-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_rename_image_webp_configurationimage_webp_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="group",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Видимость"),
        ),
        migrations.AddField(
            model_name="group",
            name="key",
            field=models.CharField(
                blank=True,
                help_text="Используется в сочетании с видимостью, нужно для выбора группы характеристик по ключу",
                max_length=100,
                verbose_name="Ключ",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название группы"
            ),
        ),
    ]
