# Generated by Django 6.0.1 on 2026-02-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_configuration_slug_group_is_visible_group_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=14,
                null=True,
                verbose_name="цена",
            ),
        ),
    ]
