# Generated by Django 6.0.1 on 2026-02-12 22:40

import catalog.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_configuration_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="slug",
            field=models.SlugField(
                blank=True,
                default=catalog.utils.default_configuration_slug,
                unique=True,
            ),
        ),
    ]
