# Generated by Django 6.0.1 on 2026-02-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_configuration_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название цвета"
                    ),
                ),
                (
                    "color_type",
                    models.CharField(
                        choices=[("exterior", "Экстерьер"), ("interior", "Интерьер")],
                        max_length=8,
                        verbose_name="Тип цвета",
                    ),
                ),
                (
                    "hex_code",
                    models.CharField(
                        blank=True,
                        help_text="#FF0000",
                        max_length=7,
                        verbose_name="Код цвета",
                    ),
                ),
            ],
            options={
                "verbose_name": "цвет",
                "verbose_name_plural": "Цвета",
                "unique_together": {("color_type", "name")},
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[("exterior", "Экстерьер"), ("interior", "Интерьер")],
                        max_length=8,
                        verbose_name="Тип фото",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cars/original/%Y/%m/%d",
                        verbose_name="Фото автомобиля",
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cars/webp/%Y/%m/%d"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.car",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="catalog.color",
                        verbose_name="Цвет",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото автомобиля",
                "verbose_name_plural": "Фото автомобилей",
            },
        ),
    ]
