# Generated by Django 6.0.1 on 2026-02-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_color_carimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carimage",
            name="image",
            field=models.ImageField(
                default=1,
                upload_to="cars/original/%Y/%m/%d",
                verbose_name="Фото автомобиля",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="color",
            name="hex_code",
            field=models.CharField(
                blank=True, help_text="#FF0000", max_length=7, verbose_name="Цвет"
            ),
        ),
        migrations.CreateModel(
            name="CarAdvantages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="advantages/original/%Y/%m/%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="advantages/webp/%Y/%m/%d"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantages",
                        to="catalog.car",
                        verbose_name="Автомобиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "преимущество",
                "verbose_name_plural": "Преимущества",
            },
        ),
        migrations.CreateModel(
            name="CarAdvantagesItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "car_advantages",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.caradvantages",
                        verbose_name="Пункт преимущества",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
    ]
