# Generated by Django 6.0.1 on 2026-02-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_alter_carimage_image_alter_color_hex_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caradvantagesitem",
            name="title",
            field=models.CharField(default=1, max_length=255, verbose_name="Заголовок"),
            preserve_default=False,
        ),
    ]
