# Generated by Django 6.0.1 on 2026-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_caradvantagesitem_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dealership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="Slug"
                    ),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Адрес")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Сайт")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Автосалон",
                "verbose_name_plural": "Автосалоны",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
    ]
