# Generated by Django 6.0.1 on 2026-03-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_dealership"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealership",
            name="working_hours",
            field=models.CharField(
                blank=True,
                default="Ежедневно с 09:00 до 21:00",
                max_length=100,
                verbose_name="Часы работы",
            ),
        ),
    ]
