# Generated by Django 6.0.1 on 2026-05-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_dealership_working_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealership",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="dealership",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота",
            ),
        ),
        migrations.AlterField(
            model_name="dealership",
            name="phone",
            field=models.CharField(max_length=150, verbose_name="Телефон"),
        ),
    ]
