# Generated by Django 6.0.1 on 2026-06-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_dealership_latitude_dealership_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="additional_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Дополнительное название"
            ),
        ),
    ]
