# Generated by Django 6.0.1 on 2026-06-23 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_configuration_additional_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealershipImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="dealership/original/%Y/%m/%d",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="dealership/webp/%Y/%m/%d"
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=255)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.dealership",
                        verbose_name="Изображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "Изображения",
                "ordering": ["order"],
            },
        ),
    ]
