# Generated by Django 6.0.1 on 2026-01-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ключ записи на EN"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Название поля"),
                ),
                ("value", models.TextField(verbose_name="Значение поля")),
                (
                    "desc",
                    models.TextField(blank=True, verbose_name="Описание использования"),
                ),
                (
                    "is_display_in_company_details",
                    models.BooleanField(
                        default=False, verbose_name="Отображать в карточке компании"
                    ),
                ),
                (
                    "microdata",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Микроразметка schema.org",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись о компании",
                "verbose_name_plural": "Информация о компании",
            },
        ),
        migrations.CreateModel(
            name="GeneralInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ключ записи на EN"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название поля"),
                ),
                (
                    "value",
                    models.CharField(max_length=255, verbose_name="Значение поля"),
                ),
                (
                    "desc",
                    models.TextField(blank=True, verbose_name="Описание использования"),
                ),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "Общая информация",
            },
        ),
        migrations.CreateModel(
            name="HTMLContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ключ записи на EN"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название поля"),
                ),
                ("value", models.TextField(verbose_name="Значение поля")),
                (
                    "desc",
                    models.TextField(blank=True, verbose_name="Описание использования"),
                ),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "HTML фрагменты",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название меню"
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Название пункта"
                    ),
                ),
                ("url", models.CharField(max_length=255, verbose_name="URL")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.menu",
                        verbose_name="Меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
            },
        ),
    ]
