# Generated by Django 6.0.1 on 2026-02-04 23:00

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "video_file",
                    models.FileField(
                        upload_to="hero_videos/",
                        validators=[content.validators.validate_mp4_file],
                        verbose_name="Фоновое видео MP4",
                    ),
                ),
                (
                    "car_model",
                    models.CharField(
                        help_text="Например: BAW 212",
                        max_length=50,
                        verbose_name="Модель автомобиля",
                    ),
                ),
                (
                    "main_title",
                    models.CharField(
                        help_text="Например: готов к любым дорогам",
                        max_length=200,
                        verbose_name="Главный заголовок H1",
                    ),
                ),
                (
                    "price_title",
                    models.CharField(
                        default="СПЕЦИАЛЬНАЯ ЦЕНА ОТ:",
                        help_text="Текст перед основной ценой",
                        max_length=100,
                        verbose_name="Заголовок цены",
                    ),
                ),
                (
                    "price_value",
                    models.CharField(
                        help_text="Например: 4 440 000 ₽",
                        max_length=50,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="СТАТЬ ВЛАДЕЛЬЦЕМ",
                        max_length=100,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "button_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка кнопки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Hero-секция",
                "verbose_name_plural": "Hero-секции",
                "ordering": ["-created_at"],
            },
        ),
    ]
