# Generated by Django 6.0.1 on 2026-02-04 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_herosection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosection",
            name="button_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на страницу (например /) или идентификатор блока (например #price-section)",
                max_length=100,
                null=True,
                verbose_name="Ссылка кнопки",
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="video_file",
            field=models.FileField(
                upload_to="hero_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
                verbose_name="Фоновое видео MP4",
            ),
        ),
    ]
