# Generated by Django 6.0.1 on 2026-02-05 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_herosection_button_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="bottom_button_text",
            field=models.CharField(
                default="/", max_length=100, verbose_name="Текст кнопки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="herosection",
            name="bottom_button_url",
            field=models.CharField(
                blank=True,
                help_text="Ссылка на страницу (например /) или идентификатор блока (например #price-section)",
                max_length=100,
                null=True,
                verbose_name="Ссылка кнопки",
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="bottom_description_text",
            field=models.TextField(
                blank=True,
                help_text="Текст описания под блоком видео",
                verbose_name="Текст описания",
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="bottom_title_text",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Заголовок под блоком видео",
                max_length=200,
                verbose_name="Заголовок описания",
            ),
            preserve_default=False,
        ),
    ]
