# Generated by Django 6.0.1 on 2026-02-10 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_rename_image_webp_configurationimage_webp_image"),
        ("content", "0004_herosection_bottom_button_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardConfigurationFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.TextField(max_length=200, verbose_name="Заголовок")),
                (
                    "icon",
                    models.ImageField(
                        upload_to="cards/icons/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["svg"]
                            )
                        ],
                        verbose_name="Иконка",
                    ),
                ),
                ("value", models.TextField(max_length=100, verbose_name="Значение")),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Например Л.С",
                        max_length=50,
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "особенность комплектации",
                "verbose_name_plural": "Особенности комплектации",
            },
        ),
        migrations.CreateModel(
            name="CardConfigurationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.TextField(max_length=200, verbose_name="Заголовок")),
                (
                    "image",
                    models.ImageField(
                        upload_to="cards/images/original/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpeg", "png", "jpg"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(blank=True, null=True, upload_to="cards/webp/"),
                ),
                ("alt", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CardConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.TextField(verbose_name="Описание")),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="catalog.configuration",
                        verbose_name="Комплектация",
                    ),
                ),
            ],
            options={
                "verbose_name": "карточка комплектаций",
                "verbose_name_plural": "Карточки комплектаций",
            },
        ),
    ]
