# Generated by Django 6.0.1 on 2026-02-10 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_cardconfigurationfeature_cardconfigurationimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardconfigurationfeature",
            name="card_configuration",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="content.cardconfiguration",
                verbose_name="Карточка комплектации",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cardconfigurationimage",
            name="card_configuration",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="content.cardconfiguration",
                verbose_name="Карточка комплектации",
            ),
            preserve_default=False,
        ),
    ]
