# Generated by Django 6.0.1 on 2026-02-10 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_cardconfigurationfeature_card_configuration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardconfigurationimage",
            name="description",
            field=models.TextField(default=1, verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cardconfigurationfeature",
            name="icon",
            field=models.FileField(
                upload_to="cards/icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    )
                ],
                verbose_name="Иконка",
            ),
        ),
        migrations.AlterField(
            model_name="cardconfigurationimage",
            name="title",
            field=models.TextField(max_length=100, verbose_name="Заголовок"),
        ),
    ]
