# Generated by Django 6.0.1 on 2026-02-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_cardconfigurationimage_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="Максимальная длина вопроса 255 символов",
                        max_length=255,
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Максимальная длина не ограничена",
                        verbose_name="Ответ",
                    ),
                ),
            ],
            options={
                "verbose_name": "вопрос-ответ",
                "verbose_name_plural": "Вопросы и ответы",
            },
        ),
        migrations.AlterField(
            model_name="cardconfigurationfeature",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="cardconfigurationfeature",
            name="value",
            field=models.CharField(max_length=100, verbose_name="Значение"),
        ),
    ]
