# Generated by Django 6.0.1 on 2026-02-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_rename_image_webp_configurationimage_webp_image"),
        ("content", "0008_question_alter_cardconfigurationfeature_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BawComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок блока",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "title_form",
                    models.CharField(max_length=200, verbose_name="Заголовок формы"),
                ),
                (
                    "sub_title_form",
                    models.CharField(max_length=255, verbose_name="Подзаголовок формы"),
                ),
                ("text_form", models.TextField(verbose_name="Текст формы")),
                (
                    "text_red_button",
                    models.CharField(
                        max_length=100, verbose_name="Текст красной кнопки"
                    ),
                ),
                (
                    "url_red_button",
                    models.CharField(max_length=50, verbose_name="Url красной кнопки"),
                ),
                (
                    "text_black_button",
                    models.CharField(
                        max_length=100, verbose_name="Текст черной кнопки"
                    ),
                ),
                (
                    "url_black_button",
                    models.CharField(max_length=50, verbose_name="Url черной кнопки"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="comparisons/original/",
                        verbose_name="Изображение блока",
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="comparisons/webp/"
                    ),
                ),
            ],
            options={
                "verbose_name": "форма",
                "verbose_name_plural": "Формы сравнения",
            },
        ),
        migrations.CreateModel(
            name="BawComparisonConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="catalog.configuration",
                        verbose_name="Комплектация",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="content.bawcomparison",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BawComparisonFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Свойство")),
                ("value", models.CharField(max_length=100, verbose_name="Значение")),
                (
                    "baw_comparison_configuration",
                    models.ManyToManyField(
                        related_name="features",
                        to="content.bawcomparisonconfiguration",
                        verbose_name="Конфигурация",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
    ]
