# Generated by Django 6.0.1 on 2026-02-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_bawcomparison_bawcomparisonconfiguration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bawcomparison",
            name="alt",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
