# Generated by Django 6.0.1 on 2026-02-12 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_bawcomparison_alt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bawcomparisonconfiguration",
            options={
                "verbose_name": "конфигурацию",
                "verbose_name_plural": "Сравнение конфигураций",
            },
        ),
        migrations.DeleteModel(
            name="BawComparisonFeature",
        ),
    ]
