# Generated by Django 6.0.1 on 2026-02-13 00:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_alter_bawcomparisonconfiguration_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BawTesting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок блока"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Текст под заголовком", verbose_name="Описание"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="testing/video/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4"]
                            )
                        ],
                        verbose_name="Фоновое видео MP4",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Заголовок под блоком видео",
                        max_length=255,
                        verbose_name="Второй заголовок",
                    ),
                ),
                (
                    "title_full_control",
                    models.CharField(
                        help_text="Заголовок под блоком с 3 фото",
                        max_length=255,
                        verbose_name="Третий заголовок",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Изображение в блоке полного контроля",
                        upload_to="testing/img/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(blank=True, null=True, upload_to="testing/webp/"),
                ),
                ("alt", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "блок",
                "verbose_name_plural": "Блок проходимости (контроль)",
            },
        ),
        migrations.CreateModel(
            name="BawTestingFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "icon",
                    models.FileField(
                        upload_to="testing/icons/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["svg"]
                            )
                        ],
                        verbose_name="Иконка",
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="Значение")),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Например Л.С",
                        max_length=50,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="content.bawtesting",
                        verbose_name="Блок проходимости",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BawTestingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="testing/images/", verbose_name="Изображение"
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(blank=True, null=True, upload_to="testing/webp/"),
                ),
                ("alt", models.CharField(blank=True, max_length=50)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.bawtesting",
                        verbose_name="Блок",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BawTestingItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "value",
                    models.CharField(
                        help_text="Например 2H или 4L",
                        max_length=10,
                        verbose_name="Обозначение",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.bawtesting",
                        verbose_name="Блок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункты блока механика",
                "verbose_name_plural": "Механика под полным контролем",
            },
        ),
    ]
