# Generated by Django 6.0.1 on 2026-02-13 09:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0012_bawtesting_bawtestingfeature_bawtestingimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
            ],
            options={
                "verbose_name": "блок",
                "verbose_name_plural": "Видеоблок",
            },
        ),
        migrations.AlterModelOptions(
            name="bawtestingfeature",
            options={
                "verbose_name": "особенность",
                "verbose_name_plural": "Особенности",
            },
        ),
        migrations.AlterModelOptions(
            name="bawtestingimage",
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.RemoveField(
            model_name="bawtesting",
            name="webp_image",
        ),
        migrations.AlterField(
            model_name="bawtesting",
            name="image",
            field=models.FileField(
                help_text="Изображение в блоке полного контроля",
                upload_to="testing/images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    )
                ],
                verbose_name="Изображение",
            ),
        ),
        migrations.CreateModel(
            name="VideoCardContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="video-blocks/images/", verbose_name="Превью"
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="video-blocks/webp/"
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=50)),
                (
                    "video",
                    models.FileField(
                        upload_to="video-blocks/video/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4"]
                            )
                        ],
                        verbose_name="Видео",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="content.videocard",
                        verbose_name="Блок",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
    ]
