# Generated by Django 6.0.1 on 2026-02-13 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0013_videocard_alter_bawtestingfeature_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnologyBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "description",
                    models.TextField(
                        help_text="Расположен под заголовком", verbose_name="Текст"
                    ),
                ),
            ],
            options={
                "verbose_name": "блок",
                "verbose_name_plural": "Технологии",
            },
        ),
        migrations.CreateModel(
            name="TechnologyBlockContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Текст")),
                (
                    "image",
                    models.ImageField(
                        upload_to="technology-blocks/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpeg", "png", "jpg"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="technology-blocks/webp/"
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=50)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="content.technologyblock",
                        verbose_name="блок",
                    ),
                ),
            ],
            options={
                "verbose_name": "карточка",
                "verbose_name_plural": "Карточки технологий",
            },
        ),
    ]
