# Generated by Django 6.0.1 on 2026-02-13 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0014_technologyblock_technologyblockcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "icon",
                    models.ImageField(
                        upload_to="services/icons/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["svg"]
                            )
                        ],
                        verbose_name="Иконка",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "сервис",
                "verbose_name_plural": "Сервисы",
            },
        ),
    ]
