# Generated by Django 6.0.1 on 2026-02-13 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0015_servicesblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesblock",
            name="icon",
            field=models.FileField(
                upload_to="services/icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    )
                ],
                verbose_name="Иконка",
            ),
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Текст новости")),
                ("slug", models.SlugField(unique=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "media",
                    models.ImageField(
                        upload_to="news/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "новость",
                "verbose_name_plural": "Новости (статьи)",
                "unique_together": {("title", "created_at")},
            },
        ),
        migrations.CreateModel(
            name="NewsVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Текст новости")),
                ("slug", models.SlugField(unique=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "media",
                    models.FileField(
                        upload_to="news/video/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4"]
                            )
                        ],
                        verbose_name="Видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "новость",
                "verbose_name_plural": "Новости (видео)",
                "unique_together": {("title", "created_at")},
            },
        ),
    ]
