# Generated by Django 6.0.1 on 2026-02-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0016_alter_servicesblock_icon_newsarticle_newsvideo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsarticle",
            old_name="media",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="newsvideo",
            old_name="media",
            new_name="video",
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="webp_image",
            field=models.ImageField(blank=True, null=True, upload_to="news/webp/"),
        ),
    ]
