# Generated by Django 6.0.1 on 2026-02-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_caradvantagesitem_title"),
        ("content", "0017_rename_media_newsarticle_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dealer", models.CharField(max_length=255, verbose_name="Дилер")),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Фамилия"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "agreement",
                    models.BooleanField(
                        default=False,
                        verbose_name="Согласие на обработку персональных данных",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="car_applications",
                        to="catalog.configuration",
                        verbose_name="Комплектация",
                    ),
                ),
                (
                    "inside_color",
                    models.ForeignKey(
                        limit_choices_to={"color_type": "interior"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inside_applications",
                        to="catalog.color",
                        verbose_name="Цвет интерьера",
                    ),
                ),
                (
                    "outside_color",
                    models.ForeignKey(
                        limit_choices_to={"color_type": "exterior"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outside_applications",
                        to="catalog.color",
                        verbose_name="Цвет экстерьера",
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
