# Generated by Django 6.0.1 on 2026-02-28 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0018_carapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                ("description", models.TextField(verbose_name="Отзыв")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="history/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(blank=True, null=True, upload_to="history/webp/"),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "Отзывы клиентов",
            },
        ),
        migrations.CreateModel(
            name="OurAdventure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "video",
                    models.FileField(
                        upload_to="our_adventure/video/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4"]
                            )
                        ],
                        verbose_name="Видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "приключение",
                "verbose_name_plural": "Наши приключения",
            },
        ),
        migrations.CreateModel(
            name="Society",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Ключ записи"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "button_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок кнопки"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Текст кнопки"
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="URL кнопки"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="society/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(blank=True, null=True, upload_to="society/webp/"),
                ),
            ],
            options={
                "verbose_name": "сообщество",
                "verbose_name_plural": "Сообщества",
            },
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="is_main",
            field=models.BooleanField(
                default=False, verbose_name="Показывать на главной странице"
            ),
        ),
    ]
