# Generated by Django 6.0.1 on 2026-02-28 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0019_history_ouradventure_society_newsarticle_is_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Ключ баннера"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="banner/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(blank=True, null=True, upload_to="banner/webp/"),
                ),
            ],
            options={
                "verbose_name": "баннер",
                "verbose_name_plural": "Баннеры",
            },
        ),
    ]
