# Generated by Django 6.0.1 on 2026-03-01 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="ouradventure",
            name="image",
            field=models.ImageField(
                default=1,
                upload_to="our_adventure/images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
                verbose_name="Обложка",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ouradventure",
            name="webp_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="our_adventure/webp/"
            ),
        ),
    ]
