# Generated by Django 6.0.1 on 2026-03-01 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0021_ouradventure_image_ouradventure_webp_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="society",
            name="webp_image_mobile",
            field=models.ImageField(
                default=1,
                help_text="Вертикальное изображение используется строго для мобильной версии",
                upload_to="society/webp/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["webp"]
                    )
                ],
                verbose_name="Изображение для мобильной версии",
            ),
            preserve_default=False,
        ),
    ]
