# Generated by Django 6.0.1 on 2026-03-01 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0022_society_webp_image_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsvideo",
            name="image",
            field=models.ImageField(
                default=1,
                upload_to="news/images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
                verbose_name="Обложка",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newsvideo",
            name="webp_image",
            field=models.ImageField(blank=True, null=True, upload_to="news/webp/"),
        ),
    ]
