# Generated by Django 6.0.1 on 2026-03-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0023_newsvideo_image_newsvideo_webp_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="key",
            field=models.CharField(
                default=1, max_length=20, verbose_name="Код страницы"
            ),
            preserve_default=False,
        ),
    ]
