# Generated by Django 6.0.1 on 2026-03-01 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0024_menu_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryBaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "period",
                    models.CharField(blank=True, max_length=20, verbose_name="Период"),
                ),
                (
                    "year",
                    models.IntegerField(
                        max_length=4,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                        verbose_name="Год",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="history/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(blank=True, null=True, upload_to="history/webp/"),
                ),
            ],
            options={
                "verbose_name": "веха",
                "verbose_name_plural": "Вехи истории",
            },
        ),
    ]
