# Generated by Django 6.0.1 on 2026-03-01 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0025_historybaw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historybaw",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2050),
                ],
                verbose_name="Год",
            ),
        ),
    ]
