# Generated by Django 6.0.1 on 2026-03-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0026_alter_historybaw_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("vk", "ВКонтакте"),
                            ("telegram", "Telegram"),
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("whatsapp", "WhatsApp"),
                            ("viber", "Viber"),
                            ("ok", "Одноклассники"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Платформа",
                    ),
                ),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Например: fa-brands fa-vk",
                        max_length=100,
                        verbose_name="CSS-класс иконки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
    ]
