# Generated by Django 6.0.1 on 2026-03-09 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0027_socialnetwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialnetwork",
            name="icon",
            field=models.FileField(
                blank=True,
                help_text="Загрузите файл в формате .svg",
                null=True,
                upload_to="social/icons/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    )
                ],
                verbose_name="Иконка (SVG)",
            ),
        ),
    ]
