# Generated by Django 6.0.1 on 2026-03-10 09:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0028_alter_socialnetwork_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название темы"),
                ),
            ],
            options={
                "verbose_name": "тема вопросов",
                "verbose_name_plural": "Темы вопросов",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="content.questiontopic",
                verbose_name="Тема",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="content_que_search__536136_gin"
            ),
        ),
    ]
