# Generated by Django 6.0.1 on 2026-03-10 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0029_questiontopic_question_search_vector_question_topic_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="content.questiontopic",
                verbose_name="Тема",
            ),
            preserve_default=False,
        ),
    ]
