# Generated by Django 6.0.1 on 2026-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0030_alter_question_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "is_sent_to_crm",
                    models.BooleanField(
                        default=False, verbose_name="Обработан в AmoCRM"
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "Заявки на обратный звонок",
                "ordering": ["-created_at"],
            },
        ),
    ]
