# Generated by Django 6.0.1 on 2026-03-27 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0031_callbackrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="special_offers/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "webp_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="special_offers/webp/"
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "valid_from",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "спецпредложение",
                "verbose_name_plural": "Спецпредложения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestDriveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Фамилия"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "desired_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Желаемая дата"
                    ),
                ),
                (
                    "desired_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Желаемое время"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "consent",
                    models.BooleanField(
                        default=False,
                        verbose_name="Согласие на обработку персональных данных",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "is_sent_to_crm",
                    models.BooleanField(
                        default=False, verbose_name="Обработан в AmoCRM"
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "Заявки на тест-драйв",
                "ordering": ["-created_at"],
            },
        ),
    ]
