# Generated by Django 6.0.1 on 2026-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0032_specialoffer_testdriverequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesblock",
            name="is_popup",
            field=models.BooleanField(
                default=True, verbose_name="Показывать модальное окно"
            ),
        ),
    ]
