# Generated by Django 6.0.1 on 2026-05-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0033_servicesblock_is_popup"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("home", "Главная"),
                            ("our-world", "Наш мир"),
                            ("about", "О компании"),
                            ("news", "Новости"),
                            ("buyers", "Покупателям"),
                            ("test-drive", "Тест-драйв"),
                            ("comparison", "Сравнение комплектаций"),
                            ("special-offer", "Спецпредложения"),
                            ("corporate", "Корпоративным клиентам"),
                            ("stories", "Истории клиентов"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Страница",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Рекомендуемая длина: до 60 символов",
                        max_length=200,
                        verbose_name="SEO Title",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Рекомендуемая длина: 120–160 символов",
                        max_length=500,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Через запятую",
                        max_length=500,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="OG Title"
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="OG Description"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Рекомендуемый размер: 1200×630px",
                        null=True,
                        upload_to="seo/og/",
                        verbose_name="OG Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO страницы",
                "verbose_name_plural": "SEO страниц",
            },
        ),
    ]
