# Generated by Django 6.0.1 on 2026-06-11 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0034_seopage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historybaw",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="history/images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
                verbose_name="Изображение",
            ),
        ),
    ]
