# Generated by Django 6.0.1 on 2026-06-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0035_alter_historybaw_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsefulMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "file",
                    models.FileField(
                        upload_to="useful_materials/", verbose_name="Файл"
                    ),
                ),
            ],
            options={
                "verbose_name": "полезный материал",
                "verbose_name_plural": "Полезные материалы",
            },
        ),
    ]
