# Generated by Django 6.0.1 on 2026-06-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0036_usefulmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ouradventure",
            name="ext_url",
            field=models.URLField(blank=True, null=True, verbose_name="Внешняя ссылка"),
        ),
    ]
