# Generated by Django 6.0.1 on 2026-06-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0037_ouradventure_ext_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="carapplication",
            name="is_sent_to_crm",
            field=models.BooleanField(default=False, verbose_name="Отправлено в CRM"),
        ),
    ]
